### ISSUE TITLE
Two systems fail to return data for /query/codex/biostats call

### ISSUE THREAD

**Issue by teptec** [canonn-science/Canonn-GCloud#1]
I have noticed that hits on /query/codex/biostats fails for two systems.
https://us-central1-canonn-api-236217.cloudfunctions.net/query/codex/biostats?id=2553098013019
https://us-central1-canonn-api-236217.cloudfunctions.net/query/codex/biostats?id=3382387413698

These are both pretty busy systems, but I note that Adityan loads fine and it has more bodies and more stations:
https://us-central1-canonn-api-236217.cloudfunctions.net/query/codex/biostats?id=5031520572122

**Comment by NoFoolLikeOne** [comment]
Looks like we are hitting limits on the size of the output so stripping factions and stations

**Comment by NoFoolLikeOne** [comment]
This is fixed for these cases but my be limited in others.
