### ISSUE TITLE
Bio guesses omitted in some cases

### ISSUE THREAD

**Issue by Valjean42** [canonn-science/Canonn-GCloud#3]
It seems when trying to guess possible biology signals, the code looks at a value called "fdevname" for each species. That value is used to extract a needed star type. However, in some species, the star type might be replaced with a material, but the code assumes it's a star type and, not finding a star with that type in the system, declares the species as impossible on planets where it can appear.
The function in question is species_star(species) in query/localpackage/codex.py

**Comment by NoFoolLikeOne** [comment]
fixed
